- hosts: vm's
  sudo: yes
 tasks:
    - name: Installs nginx web server
      apt: pkg=nginx state=installed update_cache=true
      notify:
        - start nginx
-upload html file to host
   copy: src=static_files/index.html dest=/usr/share/nginx/www/ mode=0644
  handlers:
    - name: start nginx
      service: name=nginx state=started

vars_files:
    - vars_nginx.yaml


